export { defineCommand } from './command/define-command';
export type { AnyCommand, Command } from './command/define-command';
export type { CommandContext, DomainEvent } from './command/context';
export { runCommand, checkPermission } from './command/run-command';
export type { AuditEntry, RunOptions } from './command/run-command';
export { commands, getCommand } from './command/registry';
export { updateEntity } from './commands/org/update-entity';
export { createLead } from './commands/crm/create-lead';
export { listEntities } from './queries/org/list-entities';
export { toEntityDto } from './queries/org/entity-dto';
export { listLeads, countLeads } from './queries/crm/list-leads';
export type { LeadPage, ListLeadsOptions } from './queries/crm/list-leads';
export { toLeadDto } from './queries/crm/lead-dto';
