import { v7 as uuidv7 } from 'uuid';
import { z } from 'zod';

/** UUIDv7 primary keys, generated by the server or the field client (ADR 0006). */
export const IdSchema = z.uuidv7();
export type Id = z.infer<typeof IdSchema>;

export function newId(): Id {
  return uuidv7();
}

/** The time a UUIDv7 id was made: its first 48 bits are Unix milliseconds. */
export function idTime(id: string): Date {
  return new Date(Number.parseInt(id.replaceAll('-', '').slice(0, 12), 16));
}

/** `entities.id` is a small fixed set and stays a smallint (ADR 0006). */
export const EntityIdSchema = z.number().int().min(1).max(32767);
export type EntityId = z.infer<typeof EntityIdSchema>;

/**
 * The key a caller sends so a retried call acts once (docs/06-api.md §1): any UUID, since browsers
 * and the field app generate version 4 ones with `crypto.randomUUID()`.
 */
export const IdempotencyKeySchema = z.uuid();
export type IdempotencyKey = z.infer<typeof IdempotencyKeySchema>;
