import { v7 as uuidv7 } from 'uuid';
import { z } from 'zod';

/** UUIDv7 primary keys, generated by the server or the field client (ADR 0006). */
export const IdSchema = z.uuidv7();
export type Id = z.infer<typeof IdSchema>;

export function newId(): Id {
  return uuidv7();
}

/** `entities.id` is a small fixed set and stays a smallint (ADR 0006). */
export const EntityIdSchema = z.number().int().min(1).max(32767);
export type EntityId = z.infer<typeof EntityIdSchema>;
