import { PERMISSION_KEYS, permissionModule, type PermissionKey } from '@shakti/contracts';

/** Internal descriptions for Admin › Roles. These are read by Executives, so they stay plain. */
const DESCRIPTIONS: Record<PermissionKey, string> = {
  'crm.lead.read': 'See leads',
  'crm.lead.write': 'Add and update leads',
  'crm.lead.assign': 'Assign leads to callers',
  'crm.lead.merge': 'Merge duplicate leads',
  'crm.account.read': 'See customers',
  'crm.account.write': 'Add and update customers',
  'calls.dial': 'Make calls from the app',
  'calls.recording.listen': 'Listen to call recordings',
  'sales.quote.create': 'Create quotes',
  'sales.quote.send': 'Send quotes to customers',
  'sales.order.create': 'Create sales orders',
  'sales.order.confirm': 'Confirm sales orders',
  'sales.order.cancel': 'Cancel sales orders',
  'sales.credit.release': 'Release a dealer credit hold',
  'pricing.read': 'See price lists',
  'pricing.write': 'Change price lists',
  'tax.rates.write': 'Maintain GST rates',
  'inventory.stock.read': 'See stock',
  'inventory.stock.move': 'Move stock',
  'inventory.stock.adjust': 'Adjust stock with a reason',
  'inventory.dispatch.write': 'Create and update dispatches',
  'inventory.eway.write': 'Enter e-way bill details',
  'procurement.po.write': 'Create purchase orders',
  'procurement.grn.write': 'Record goods received',
  'procurement.rate.read': 'See supplier rates',
  'projects.read': 'See projects',
  'projects.write': 'Update projects',
  'projects.gate.approve': 'Approve subsidy and project gates',
  'projects.qc.signoff': 'Sign off quality checks',
  'projects.schedule.write': 'Schedule engineer visits',
  'documents.read': 'See documents',
  'documents.write': 'Add documents',
  'documents.sensitive.read': 'See identity documents',
  'finance.proforma.write': 'Create proformas',
  'finance.payment.write': 'Record payments',
  'finance.recon.write': 'Reconcile with Tally',
  'finance.cost.read': 'See costs and margins',
  'finance.expense.approve': 'Approve expense claims',
  'hr.employee.write': 'Maintain employee records',
  'hr.attendance.manage': 'Manage attendance',
  'hr.leave.approve': 'Approve leave',
  'hr.incentive.manage': 'Manage incentives',
  'hr.export': 'Export salary and incentive sheets',
  'knowledge.vault.read.staff': 'Search staff knowledge',
  'knowledge.vault.read.management': 'Search management knowledge',
  'knowledge.vault.read.exec': 'Search executive knowledge',
  'knowledge.playbook.approve': 'Approve Playbook directives',
  'agents.inbox.act': 'Act on Agent Inbox items',
  'agents.autonomy.write': 'Change agent autonomy',
  'agents.killswitch': 'Pause agents',
  'voice.use': 'Talk to Shakti',
  'reports.export': 'Export reports',
  'audit.read': 'See the audit trail',
  'admin.users.write': 'Manage users',
  'admin.roles.write': 'Manage roles',
  'admin.entities.write': 'Manage entities',
  'admin.integrations.write': 'Manage integrations',
  'admin.flags.write': 'Manage feature flags',
};

export const PERMISSION_SEED = PERMISSION_KEYS.map((key) => ({
  key,
  module: permissionModule(key),
  description: DESCRIPTIONS[key],
}));
