import {
  PERMISSION_KEYS,
  type AgentRoleKey,
  type PermissionGrant,
  type PermissionKey,
  type RoleKey,
  type Scope,
  type StaffRoleKey,
  type SystemRoleKey,
  AGENT_MATRIX,
  SYSTEM_MATRIX,
} from '@shakti/contracts';

type StaffRow = Partial<Record<StaffRoleKey, Scope>>;

const EXEC: StaffRow = { executive: 'all' };

/**
 * docs/07-security.md §3.2 transcribed cell by cell. Column order there: Executive, GM, Sales Lead,
 * CC, LC, Store, Inventory, Project Mgr, Field, Accounts, HR. This object is the seed and the
 * oracle for the security suite.
 */
export const STAFF_MATRIX: Record<PermissionKey, StaffRow> = {
  'crm.lead.read': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
    project_manager: 'entity',
    accounts: 'entity',
  },
  'crm.lead.write': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
  },
  'crm.lead.assign': { ...EXEC, general_manager: 'entity', sales_team_lead: 'team' },
  'crm.lead.merge': { ...EXEC, general_manager: 'entity', sales_team_lead: 'team' },
  'crm.account.read': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
    inventory_manager: 'entity',
    project_manager: 'entity',
    field_engineer: 'own',
    accounts: 'entity',
  },
  'crm.account.write': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
    project_manager: 'entity',
  },
  'crm.config.write': { ...EXEC },
  'calls.dial': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
  },
  'calls.log': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
  },
  'calls.recording.listen': { ...EXEC, general_manager: 'entity', sales_team_lead: 'team' },
  'sales.quote.create': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_lc: 'own',
    store_manager: 'own',
  },
  'sales.quote.send': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_lc: 'own',
    store_manager: 'own',
  },
  'sales.order.create': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_lc: 'own',
    store_manager: 'own',
  },
  'sales.order.confirm': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_lc: 'own',
    store_manager: 'own',
  },
  'sales.order.cancel': { ...EXEC, general_manager: 'entity' },
  'sales.credit.release': { ...EXEC },
  'pricing.read': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'entity',
    tele_caller_cc: 'entity',
    tele_caller_lc: 'entity',
    store_manager: 'entity',
    inventory_manager: 'entity',
    project_manager: 'entity',
    accounts: 'entity',
  },
  'pricing.write': { ...EXEC },
  'catalogue.write': { ...EXEC, general_manager: 'entity', inventory_manager: 'entity' },
  'tax.rates.write': { ...EXEC, accounts: 'entity' },
  'inventory.stock.read': {
    ...EXEC,
    general_manager: 'entity',
    tele_caller_lc: 'entity',
    store_manager: 'entity',
    inventory_manager: 'entity',
    project_manager: 'entity',
    field_engineer: 'own',
    accounts: 'entity',
  },
  'inventory.stock.move': { ...EXEC, inventory_manager: 'entity', field_engineer: 'own' },
  'inventory.stock.adjust': { ...EXEC, inventory_manager: 'entity' },
  'inventory.dispatch.write': {
    ...EXEC,
    general_manager: 'entity',
    inventory_manager: 'entity',
    project_manager: 'entity',
  },
  'inventory.eway.write': { ...EXEC, inventory_manager: 'entity', accounts: 'entity' },
  'inventory.warranty.write': { ...EXEC, inventory_manager: 'entity' },
  'procurement.po.write': { ...EXEC, inventory_manager: 'entity' },
  'procurement.grn.write': { ...EXEC, inventory_manager: 'entity' },
  'procurement.rate.read': { ...EXEC, inventory_manager: 'entity', accounts: 'entity' },
  'projects.read': {
    ...EXEC,
    general_manager: 'entity',
    tele_caller_lc: 'own',
    project_manager: 'entity',
    field_engineer: 'own',
    accounts: 'entity',
  },
  'projects.write': {
    ...EXEC,
    general_manager: 'entity',
    project_manager: 'entity',
    field_engineer: 'own',
  },
  'projects.gate.approve': { ...EXEC, general_manager: 'entity', project_manager: 'entity' },
  'projects.qc.signoff': { ...EXEC, general_manager: 'entity', project_manager: 'entity' },
  'projects.schedule.write': { ...EXEC, general_manager: 'entity', project_manager: 'entity' },
  'documents.read': {
    ...EXEC,
    general_manager: 'entity',
    tele_caller_lc: 'own',
    store_manager: 'own',
    project_manager: 'entity',
    field_engineer: 'own',
    accounts: 'entity',
  },
  'documents.write': {
    ...EXEC,
    general_manager: 'entity',
    tele_caller_lc: 'own',
    store_manager: 'own',
    project_manager: 'entity',
    field_engineer: 'own',
    accounts: 'entity',
  },
  'documents.sensitive.read': { ...EXEC, project_manager: 'entity', accounts: 'entity' },
  'finance.proforma.write': { ...EXEC, accounts: 'entity' },
  'finance.payment.write': { ...EXEC, accounts: 'entity' },
  'finance.recon.write': { ...EXEC, accounts: 'entity' },
  'finance.cost.read': { ...EXEC, accounts: 'entity' },
  'finance.expense.submit': {
    executive: 'own',
    general_manager: 'own',
    sales_team_lead: 'own',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
    inventory_manager: 'own',
    project_manager: 'own',
    field_engineer: 'own',
    accounts: 'own',
    hr_admin: 'own',
  },
  'finance.expense.approve': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    project_manager: 'entity',
    accounts: 'entity',
  },
  'finance.expense.verify': { ...EXEC, accounts: 'entity' },
  'hr.employee.write': { ...EXEC, hr_admin: 'all' },
  'hr.attendance.manage': { ...EXEC, hr_admin: 'all' },
  'hr.leave.approve': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    hr_admin: 'all',
  },
  'hr.incentive.manage': { ...EXEC, hr_admin: 'all' },
  'hr.export': { ...EXEC, accounts: 'all', hr_admin: 'all' },
  'knowledge.vault.read.staff': {
    executive: 'all',
    general_manager: 'all',
    sales_team_lead: 'all',
    tele_caller_cc: 'all',
    tele_caller_lc: 'all',
    store_manager: 'all',
    inventory_manager: 'all',
    project_manager: 'all',
    field_engineer: 'all',
    accounts: 'all',
    hr_admin: 'all',
  },
  'knowledge.vault.read.management': { ...EXEC, general_manager: 'all', accounts: 'all' },
  'knowledge.vault.read.exec': { ...EXEC },
  'knowledge.playbook.approve': { ...EXEC },
  'agents.inbox.act': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
    inventory_manager: 'entity',
    project_manager: 'entity',
    accounts: 'entity',
  },
  'agents.autonomy.write': { ...EXEC },
  'agents.killswitch': { ...EXEC, general_manager: 'all' },
  'voice.use': { ...EXEC, general_manager: 'all' },
  'reports.export': {
    ...EXEC,
    general_manager: 'entity',
    sales_team_lead: 'team',
    inventory_manager: 'entity',
    project_manager: 'entity',
    accounts: 'entity',
    hr_admin: 'all',
  },
  'audit.read': { ...EXEC, general_manager: 'entity', accounts: 'entity' },
  'imports.write': { ...EXEC, general_manager: 'entity' },
  'profile.write': {
    executive: 'own',
    general_manager: 'own',
    sales_team_lead: 'own',
    tele_caller_cc: 'own',
    tele_caller_lc: 'own',
    store_manager: 'own',
    inventory_manager: 'own',
    project_manager: 'own',
    field_engineer: 'own',
    accounts: 'own',
    hr_admin: 'own',
  },
  'admin.users.write': { ...EXEC },
  'admin.roles.write': { ...EXEC },
  'admin.entities.write': { ...EXEC },
  'admin.integrations.write': { ...EXEC },
  'admin.flags.write': { ...EXEC },
  'integrations.dlq.replay': { ...EXEC },
  // The platform's file checks and the import worker's stop; no person's role holds them
  // (SECURITY §3.3).
  'files.process': {},
  'imports.process': {},
  // The platform's nightly rescoring of leads; no person's role holds it (SECURITY §3.3).
  'crm.score.refresh': {},
  // The platform's nightly search for duplicates; no person's role holds it (SECURITY §3.3).
  'crm.duplicates.scan': {},
  // The platform's daily expiry of lapsed quotes; no person's role holds it (SECURITY §3.3).
  'sales.quote.expire': {},
};

/** Agent principal permission sets (docs/07-security.md §3.3), from the contracts the runtime shares. */
export { AGENT_MATRIX };

/** The system principal's grants (docs/07-security.md §3.3), from the contracts the workers share. */
export { SYSTEM_MATRIX };

/** Grants for any role, staff, agent or system, from the matrices above. */
export function grantsForRole(roleKey: RoleKey): PermissionGrant[] {
  if (roleKey.startsWith('agent:')) return [...AGENT_MATRIX[roleKey as AgentRoleKey]];
  if (roleKey.startsWith('system:')) return [...SYSTEM_MATRIX[roleKey as SystemRoleKey]];
  const staff = roleKey as StaffRoleKey;
  const grants: PermissionGrant[] = [];
  for (const key of PERMISSION_KEYS) {
    const scope = STAFF_MATRIX[key][staff];
    if (scope) grants.push({ key, scope });
  }
  return grants;
}
